 
FIELDS = {
    "id_visit": "idvisit",
    "referrer_type": "referrertype",
    "segments": "Segments",
    "url": "URL",
    "fil_type_site": "FIL_TYPE_SITE",
    "actions": "Actions",
    "visitor_type": "Type_visiteur",
    "tag_neva": "Tag_Neva",
    "value_goal": "goal",
    "value_action": "action",
    "xx_timestamp": "Date_Visite",
    "str_date_format": "dd/MM/yyyy",
    "xx_jour": "Jour_Visite",
    "type": "Type_CTA",
    "timespent": "Duree_Navigation",
    "goal_name": "Libelle_CTA",
    "goal_conversions": "Conversion_Rebond",
    "initial_visitor_id": "Identifiant_Visiteur",
    "campaign_id": "Identifiant_Campagne",
    "tps_passe_visit": "TpsPasseVisit",
    "tps_passe_total": "tps_passe_total",
    "type_site": "Type_Site",
    "type_page": "Type_Pages",
    "nb_rebond": "NbRebond",
    "visiteur_engage": "Visiteur_engage",
    "nb_page_vue": "nb_page_vue",
    "ind_pa_nb_leads": "IND_PA_NB_LEADS",
    "ind_pa_audience_exposee": "IND_PA_AUDIENCE_EXPOSEE",
    "visit_type_leads_dmd_contact": "Visit_type_leads_Dmd_contact",
    "visit_type_leads_crea_compte": "Visit_type_leads_CreaCompte",
    "visit_type_leads_abo_localtis_hebdo": "Visit_type_leads_AboLocH",
    "visit_type_leads_abo_localtis_quotidien": "Visit_type_leads_AboLocQ",
    "visit_type_leads_dmd_pret": "Visit_type_leads_Dmd_pret",
    "visit_type_leads_not_sel": "Visit_type_leads_NotSel",
    "fil_directions_regionales": "FIL_DIRECTIONS_REGIONALES",
    "nb_rows": "nbRows",
    "visit_duration": "Duree_de_visite",
    "duree_affichage": "DureeAffichage",
    "nb_entree": "nb_entree",
    "nb_entree_home": "nb_entreehome",
    "visiteur_qualifie": "Visiteur_qualifie",
    "visiteur_connu": "Visiteur_connu",
    "nb_rebond_home": "NbRebondHome",
    "timespent_pretty": "timespentpretty",
    "page_view_position": "position_page",
    "url_bdt": "https://www.banquedesterritoires.fr/",
    "page_vue_home": "pageVuesHome",
    "timespent_home": "TimespentHome",
    "nb_leads": "nb_Leads",
    "page_title": "Titre_de_Page",
    "type_page_categorie_de_contenu": "categorie_de_contenu",
    "type_page_programme_gouvernemental": "programme_gouvernemental",
    "type_page_type_de_contenu": "Type_Contenu",
    "is_second_page": "is_second_Page",
    "referrer_type_name": "Type_de_Source",
    "campaign_name": "Identifiant_Diffusion",
    "source_traffic": "SourceTraffic",
}

GOALNAMES = [
    "Demande de contact",
    "User Account Creation",
    "Abonnement Localtis Hebdomadaire",
    "Abonnement Localtis Quotidienne",
    "FE- Parcours de demande de prets",
]

TYPE_PAGE = {"localtis": "Localtis", "marketing_de_loffre": "Marketing_de_loffre"}

KPI_FIELDS_TRACKING = [
    FIELDS.get("initial_visitor_id"),
    FIELDS.get("id_visit"),
    FIELDS.get("xx_jour"),
    FIELDS.get("campaign_id"),
    FIELDS.get("referrer_type"),
    FIELDS.get("visiteur_qualifie"),
    FIELDS.get("visiteur_connu"),
    FIELDS.get("visiteur_engage"),
    FIELDS.get("segments"),
    FIELDS.get("nb_rebond"),
    FIELDS.get("nb_rebond_home"),
    FIELDS.get("type_site"),
    FIELDS.get("fil_directions_regionales"),
]

KPI_FIELDS_TRACKING_URL = [
    FIELDS.get("xx_jour"),
    FIELDS.get("url"),
    FIELDS.get("is_second_page"),
    FIELDS.get("type_page_type_de_contenu"),
    TYPE_PAGE.get("localtis"),
    TYPE_PAGE.get("marketing_de_loffre"),
    FIELDS.get("source_traffic"),
    FIELDS.get("referrer_type_name"),
]
