 
FIELDS = {
    "nom_operation": "nom_operation",
    "libelle_operation": "libelle_operation",
    "typologie_operation": "typologie_operation",
    "date_creation": "date_creation",
    "mail_contact": "adresse_mail_contact",
    "itempsfort": "itempsfort",
    "libelle_temps_fort_operation": "libelle_temps_fort_operation",
    "hub_id_client": "hub_identifiant_client",
    "libelle_url": "libelle_url",
    "libelle_fonction": "libelle_fonction",
    "code_segment": "code_segment",
    "nom_region": "nom_region",
    "libelle_segment": "libelle_segment",
    "id_delivery": "id_delivery",
    "sinternalname": "sinternalname",
    "raison_echec": "raison_echec",
    "type_de_click": "type_de_click",
    "nbRows": "nbRows",
    "itodeliver": "itodeliver",
    "volume_emails_delivres": "volume_emails_delivres",
    "volume_ouverture": "volume_ouverture",
    "volume_click": "volume_click",
    "volume_desinscription": "volume_desinscription",
}

JOINT_KEYS = {
    "id_campagne": "identifiant_campagne",
    "id_operation_hub": "identifiant_operation_hub",
    "id_delivery": "id_delivery",
    "id_url": "iurlid",
    "id_trackingurl": "identifiant_trackingurl",
    "id_logmsg": "id_logmessage",
    "id_msg": "imsgid",
    "hub_id_client": "hub_identifiant_client",
    "id_rcpt_fct": "id_recipient_fonction",
}

KPI_FIELDS = [
    FIELDS.get("nom_operation"),
    FIELDS.get("libelle_operation"),
    FIELDS.get("typologie_operation"),
    FIELDS.get("date_creation"),
    FIELDS.get("itempsfort"),
    FIELDS.get("libelle_temps_fort_operation"),
    FIELDS.get("id_delivery"),
    FIELDS.get("sinternalname"),
    FIELDS.get("hub_id_client"),
    FIELDS.get("libelle_fonction"),
    FIELDS.get("code_segment"),
    FIELDS.get("nom_region"),
    FIELDS.get("libelle_segment"),
    FIELDS.get("libelle_url"),
    FIELDS.get("type_de_click"),
    FIELDS.get("nbRows"),
]
